trigger:
- master

pool:
  vmImage: ubuntu-latest

jobs:
  - template: build-and-push-template.yaml
    parameters:
      subfolder: connect
  - template: build-and-push-template.yaml
    parameters:
      subfolder: schema-registry-with-postgres-driver
