parameters:
  - name: subfolder
    type: string
    default: false

jobs:
  - job: ${{ parameters.subfolder }}
    steps:
      - bash: |
          IMAGE_TAG=$(cat ./${{ parameters.subfolder }}/version)
          echo $IMAGE_TAG
          echo "##vso[task.setvariable variable=tag;isOutput=true]$IMAGE_TAG"
        name: ${{ parameters.subfolder }}
        displayName: get ${{ parameters.subfolder }} version
      - task: Docker@2
        displayName: Build ${{ parameters.subfolder }} image
        inputs:
          command: "build"
          Dockerfile: "./${{ parameters.subfolder }}/Dockerfile"
          arguments: "-t ${{ parameters.subfolder }}:$(${{ parameters.subfolder }}.tag)"
      - task: AWSShellScript@1
        inputs:
          awsCredentials: 'datadelivery-aws-deploy'
          regionName: 'eu-central-1'
          scriptType: 'inline'
          inlineScript: |
            aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/v1w7b9k4
            docker tag ${{ parameters.subfolder }}:$(${{ parameters.subfolder }}.tag) public.ecr.aws/v1w7b9k4/${{ parameters.subfolder }}:$(${{ parameters.subfolder }}.tag)
            docker push public.ecr.aws/v1w7b9k4/${{ parameters.subfolder }}:$(${{ parameters.subfolder }}.tag)
        displayName: Push ${{ parameters.subfolder }} image